name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Formatting
        run: uv run --dev ruff format --check

      - name: Lint
        run: uv run --dev ruff check

      - name: Type check
        run: uv run --dev pyright

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Test
        run: uv run --dev pytest --cov-config=.coveragerc --cov-branch --cov=src/neural_chaos/ --cov-report=xml src/neural_chaos/tests/

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: chicago-aiscience/lu-neural-chaos
          files: coverage.xml

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Warm up uv
# If you remove this step, workflow will crash because codspeed doesn't like setting up the .venv
        run: uv run python --version

      - name: Bench
        uses: CodSpeedHQ/action@v3
        with:
          run: uv run --dev pytest src/neural_chaos/benches/ --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
